# Generated by Django 2.1.7 on 2019-04-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='App',
        ),
    ]
